dist: trusty
language: julia
os:
  - linux
  - osx
julia:
  - nightly
  - 0.6
matrix:
  allow_failures:
    - julia: nightly 
notifications:
  email: false 
before_script:
  - julia -e 'Pkg.clone("https://github.com/JuliaAstro/SPICE.jl.git", "SPICE"); Pkg.build("SPICE"); Pkg.add("DifferentialEquations")'
after_success:
  - julia -e 'cd(Pkg.dir("FlightSimulator")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("FlightSimulator")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'